import Link from "next/link";

export const metadata = { title: "Privacy Policy · Gate to Glory" };

const SECTIONS: { h: string; b: string }[] = [
  {
    h: "🛄 What we hoover up",
    b: "Your name, your email, and your Google mugshot — purely so we can pin your face next to a flag and watch your team get knocked out. That is genuinely the lot. We did not ask for your inside-leg measurement and we politely decline to receive it.",
  },
  {
    h: "✈ What we do with it",
    b: "Assign you a country you've never visited, then let a washed-up Tannoy announcer named Big John roast you, by name, in front of the entire office. When Big John is asleep, this duty passes to Ballroom Pete, who is worse.",
  },
  {
    h: "⚖ Our lawful basis",
    b: "Sheer optimism, plus the fact that you clicked the big amber button. We're treating that click as legally binding.",
  },
  {
    h: "🍪 Cookies",
    b: "One (1) cookie, to remember you're checked in. The rest were binned by Big John during his nine-day shift. He is very sorry. He is not, in fact, sorry.",
  },
  {
    h: "🤝 Who we share it with",
    b: "Ballroom Pete, roughly two pints deep. We will NEVER sell your data — and between you and us, Pete reckons it wouldn't fetch much anyway.",
  },
  {
    h: "🛫 Third parties",
    b: "Match scores arrive from ESPN. The banter is generated by a robot of questionable taste. Neither of them fancies you, so kindly do not get ideas.",
  },
  {
    h: "🗄 How long we keep it",
    b: "Until the final whistle of the 2026 World Cup — or until your team ships seven, tops the Welcome Aboard booby chart, and you beg to be forgotten out of pure shame. Whichever comes first.",
  },
  {
    h: "🙋 Your rights",
    b: "The right to be gutted. The right to blame the referee. The inalienable right to insist you'd have won on penalties. And the right to ask for your data back, which we shall honour the very moment we locate the napkin we wrote it on.",
  },
  {
    h: "🦺 Security",
    b: "Your information is defended by a man in a hi-vis vest, a laminated sign reading DO NOT, and the general indifference of the universe. Sleep soundly.",
  },
  {
    h: "📣 Changes to this policy",
    b: "We may update this whenever Big John next wakes up. Continued use of the sweepstake means you're cool with it, or at least too emotionally invested to walk away now.",
  },
  {
    h: "📞 Contact us",
    b: "Shout your concerns into the departure lounge. Big John will cup a hand to his ear, nod sagely, and continue to ignore you completely. Lovely jubbly.",
  },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-runway">
      <div className="mx-auto max-w-2xl px-4 py-10">
        <Link
          href="/"
          className="font-board text-[11px] uppercase tracking-widest text-ink-dim transition hover:text-amber"
        >
          ← Back to the gate
        </Link>

        <header className="mt-6 border-b border-hairline pb-5">
          <p className="font-board text-[11px] uppercase tracking-[0.4em] text-amber/80">
            The small print
          </p>
          <h1 className="mt-2 font-display text-4xl font-extrabold text-ink">
            Privacy Policy
          </h1>
          <p className="mt-3 text-ink-dim">
            Read aloud over a crackly Tannoy by Big John, who has not slept.
            Last updated: when the kettle last boiled.
          </p>
        </header>

        <div className="mt-6 space-y-4">
          {SECTIONS.map((s) => (
            <section
              key={s.h}
              className="rounded-board border border-hairline bg-board p-5"
            >
              <h2 className="font-display text-lg font-bold text-ink">{s.h}</h2>
              <p className="mt-2 text-sm leading-relaxed text-ink-dim">{s.b}</p>
            </section>
          ))}
        </div>

        <p className="mt-8 text-center font-board text-[11px] uppercase tracking-[0.3em] text-ink-dim">
          Tray tables up. You are, as ever, a valued passenger ✈
        </p>
      </div>
    </main>
  );
}
